// GoldenPin.swift — GENERATED by tools/golden_pin.sh (do not edit by hand).
// RGBA SHA-256 of GoldenFixture.state() rendered memory / zh / battery column, and the OS build it was pinned on.
// Pinned only after the frozen v1 renderer and the current renderer agreed (RGBA + ink boxes) on all 22 golden states.
enum GoldenPin {
    static let rgbaSHA256 = "e8edc0549208d74c7fe2ad7916b7284423cddec1f289d91bf5437232646d0421"
    static let osVersion = "26A434"
    static let pinnedOn = "2026-10-02"
}
