#!/bin/bash
# golden_pin.sh [--check] [--out DIR] — v1/v2 golden compare and re-pin of `render.memory.golden` (spec §10.2).
#   1. compiles the golden harness twice: with the FROZEN v1 renderer (tools/golden/v1/, byte-identical to the v1
#      release) and with the current renderer (Sources/Render/{PanelModel,PanelRenderer,PanelRenderer+Views,L10n}.swift);
#      both include Sources/Evidence/GoldenFixture.swift (the app's golden fixture, state "app_golden")
#   2. renders the 21 v1 states + app_golden with each and compares name / RGBA SHA-256 / element ink boxes
#   3. all equal → (unless --check) rewrites Sources/Evidence/GoldenPin.swift with app_golden's hash and this OS build
#      (kern.osversion) and prints the change; any difference → refuses to pin, lists the states, exit 1
#      (inspect DIR/v1/<state>.png vs DIR/v2/<state>.png by hand)
# Measurement rects (specs=) are NOT compared: r2 changed the digit rects on purpose (design/golden/specs_diff.py).
# Output: DIR (default $TMPDIR/wokyis-golden-<pid>) holds v1.txt, v2.txt, v1/, v2/ and the two harness binaries.
# Offline; Apple toolchain only; bash 3.2 compatible. Owner: foundation (golden).
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$PWD
CHECK=0
OUT="${TMPDIR:-/tmp}/wokyis-golden-$$"
while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK=1 ;;
    --out) OUT="$2"; shift ;;
    *) echo "usage: tools/golden_pin.sh [--check] [--out DIR]" >&2; exit 2 ;;
  esac
  shift
done
mkdir -p "$OUT"
case "$OUT" in /*) ;; *) OUT="$ROOT/$OUT" ;; esac
G=tools/golden
HARNESS=("$G/GoldenStates.swift" "$G/GoldenMain.swift" "$G/AMLiteral.swift" Sources/Evidence/GoldenFixture.swift)
echo "golden_pin: compiling v1 (frozen) and v2 (current) harnesses → $OUT"
swiftc -O -parse-as-library "$G/v1/PanelModel.swift" "$G/v1/PanelRenderer.swift" "${HARNESS[@]}" -o "$OUT/g_v1"
swiftc -O -parse-as-library Sources/Render/PanelModel.swift Sources/Render/PanelRenderer.swift "Sources/Render/PanelRenderer+Views.swift" \
  Sources/Render/L10n.swift "${HARNESS[@]}" -o "$OUT/g_v2"
"$OUT/g_v1" "$OUT/v1" > "$OUT/v1.txt"
"$OUT/g_v2" "$OUT/v2" > "$OUT/v2.txt"
n=$(wc -l < "$OUT/v2.txt" | tr -d ' ')
diffs=$(paste <(cut -f1-3 "$OUT/v1.txt") <(cut -f1-3 "$OUT/v2.txt") | awk -F'\t' '$1 != $4 || $2 != $5 || $3 != $6 { print $1 }')
problems=$(awk -F'\t' '$5 != "problems=0" { print $1 " " $5 }' "$OUT/v2.txt")
if [ -n "$diffs" ]; then
  echo "golden_pin: v1 and v2 DIFFER (RGBA or ink boxes) on:" >&2
  echo "$diffs" | sed 's/^/  /' >&2
  echo "golden_pin: NOT re-pinning; compare $OUT/v1/<state>.png with $OUT/v2/<state>.png" >&2
  exit 1
fi
echo "golden_pin: v1 == v2 (RGBA + ink boxes) on all $n states"
if [ -n "$problems" ]; then echo "golden_pin: layout problems in v2: $problems" >&2; exit 1; fi
sha=$(awk -F'\t' '$1 == "app_golden" { print $2 }' "$OUT/v2.txt")
os=$(sysctl -n kern.osversion)
if [ -z "$sha" ]; then echo "golden_pin: app_golden missing from the harness output" >&2; exit 1; fi
PIN=Sources/Evidence/GoldenPin.swift
old_sha=$(sed -n 's/.*rgbaSHA256 = "\(.*\)".*/\1/p' "$PIN")
old_os=$(sed -n 's/.*osVersion = "\(.*\)".*/\1/p' "$PIN")
echo "golden_pin: app_golden sha=$sha os=$os (pinned: sha=$old_sha os=$old_os)"
if [ "$CHECK" = 1 ]; then
  if [ "$sha" = "$old_sha" ] && [ "$os" = "$old_os" ]; then echo "golden_pin: pin is current"; else echo "golden_pin: pin differs (run without --check to re-pin)"; fi
  exit 0
fi
if [ "$sha" = "$old_sha" ] && [ "$os" = "$old_os" ]; then echo "golden_pin: pin already current; nothing to do"; exit 0; fi
cat > "$PIN" <<EOF
// GoldenPin.swift — GENERATED by tools/golden_pin.sh (do not edit by hand).
// RGBA SHA-256 of GoldenFixture.state() rendered memory / zh / battery column, and the OS build it was pinned on.
// Pinned only after the frozen v1 renderer and the current renderer agreed (RGBA + ink boxes) on all $n golden states.
enum GoldenPin {
    static let rgbaSHA256 = "$sha"
    static let osVersion = "$os"
    static let pinnedOn = "$(date +%Y-%m-%d)"
}
EOF
echo "golden_pin: re-pinned $PIN: sha $old_sha → $sha, os $old_os → $os (rebuild: scripts/build.sh)"
